### ISSUE TITLE
kodi 19 demo

### ISSUE THREAD

**Issue by FalconEagleTest** [romanvm/pyxbmct.demo#2]
hi,
is there any way you can make a demo that will work on kodi 19?
i tried but all i get are errors,
thanks a lot.

**Comment by romanvm** [comment]
Spam

**Comment by FalconEagleTest** [comment]
why spam?
i really wanted to try and use it on kodi 19.

**Comment by FalconEagleTest** [comment]
hi,
sorry i posted that also in the wrong place.,
yes i can see a branch of python 3 in the video example but not for "pyxbmct.demo"
is the a python 3 version for the "pyxbmct.demo"?
thanks.

**Comment by romanvm** [comment]
Next time please do not post copy-pasted non-specific questions. PyXBMCt demo itself does not contain any Python version specific code.

**Comment by FalconEagleTest** [comment]
> 
> 
> Next time please do not post copy-pasted non-specific questions. PyXBMCt demo itself does not contain any Python version specific code.

here i tried to run it on kodi 19 and this is the error:

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'focusTexture' is an invalid keyword argument for this function
                                                   Traceback (most recent call last):
                                                     File "D:\kodi19\portable_data\addons\script.pyxbmct.demo\default.py", line 177, in <module>
                                                       window = MyAddon('PyXBMCt Demo')
                                                     File "D:\kodi19\portable_data\addons\script.pyxbmct.demo\default.py", line 24, in __init__
                                                       self.set_active_controls()
                                                     File "D:\kodi19\portable_data\addons\script.pyxbmct.demo\default.py", line 70, in set_active_controls
                                                       self.radiobutton = pyxbmct.RadioButton('Off')
                                                     File "D:\kodi19\portable_data\addons\script.module.pyxbmct\lib\pyxbmct\addonwindow.py", line 300, in __new__
                                                       return super(RadioButton, cls).__new__(cls, -10, -10, 1, 1, *args, **kwargs)
                                                   TypeError: 'focusTexture' is an invalid keyword argument for this function
what am i doing wrong?
thanks for your help
